disabled_rules:
  - force_cast
  - trailing_whitespace

line_length: 150

variable_name:
  max_length:
    warning: 50
    error: 70
  min_length:
    error: 1

excluded:
  - Capsule/Source/Foundation/Fakes
